Dev manu
WildCodeSchool/Lyon-0917-HappySens pull request #171
Opened 2018-01-08 14:30 UTC by ManuelBriand

2018-01-09 07:56 UTC, 2binfree requested changes
dev manu : c'est quelle user story ;-)
Il faut utiliser des titres et commentaires plus parlant

2018-01-09 07:56 UTC, 2binfree commented on src/AppBundle/Form/UserType.php
> +        $builder->add('firstName')->add('lastName')->add('phone')->add('email')->add('status', HiddenType::class)->add('birthdate', BirthdayType::class, ['placeholder' => array('year' => 'Year', 'mon
illisible sur une seule ligne.

2018-01-09 08:32 UTC, ManuelBriand reviewed
update de tout les formulaires en plusieures étapes

2018-01-10 16:05 UTC, closed without merging

2018-01-10 16:05 UTC, ManuelBriand commented
close